### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by stanwarri** [modestkdr/Podcastwala#1]
I'm just wondering how the automatic update of podcast items are done. Can't seem to get it to work

**Comment by Srikanth-AD** [comment]
As long as cron is setup: 
http://laravel.com/docs/5.0/artisan#scheduling-artisan-commands

https://github.com/modestkdr/Podcastwala/blob/master/app/Console/Kernel.php#L24
"updatePodcastItems" command runs twice daily

And the logic for this command is defined here:
https://github.com/modestkdr/Podcastwala/blob/master/app/Console/Commands/UpdatePodcastItems.php#L29

"updatePodcastItems" command is also available as a artisan command
![screenshot from 2015-06-27 14 08 41](https://cloud.githubusercontent.com/assets/915560/8393256/1c4eeb98-1cd6-11e5-86bd-976ed2e35c18.png)
